### PR TITLE
es6 require & amd loader support (jQuery must not be globally available)

### PR DESCRIPTION
**Pull request by ViktorHofer**
With this commit, SPUtility can now be loaded with commonjs or requirejs for example by:

```
// jQuery locally available
const $ = require('jquery');
const sputility = require('sputility')($);

// jQuery globally available
const sputility = require('sputility') // jQuery is globally available

// Or normally via script tag
```

### CODE REVIEW

**Comment by kitmenke** [comment]
Woah! So can you tell me how this would work? Can you include jQuery manually still or do you have to use common.js/require.js? I haven't used those much before so I am not familiar with how they work.

**Comment by ViktorHofer** [comment]
Heyho, sry for my late Response, pretty busy right now...

You can of course use it exactly as it was before. Regarding modules and es6 please do some Research, it's not a Topic I can explain in few words.

Hope you will accept the request. We are already using my fork in our production code.

**Comment by kitmenke** [comment]
Ok cool. I was reading up on require.js and I am going to add a test for it.

I had a couple of other issues pop up but I'll merge this soon.

**Comment by ViktorHofer** [comment]
Any updates on that?

**Pull request closed without merging**
